export const BookmarkEvents = {
  CREATE_BOOKMARK: "BOOKMARK_CREATE",
  UPDATE_READ_BOOKMARK: "BOOKMARK_UPDATE_READ",
  UPDATE_WATCH_BOOKMARK: "BOOKMARK_UPDATE_WATCH",
  REFRESH_BOOKMARKS: "BOOKMARKS_REFRESH",
  DELETE_BOOKMARK: "BOOKMARK_DELETE",
}
