/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/anime-watch`; params?: Router.UnknownInputParams; } | { pathname: `/demohtml`; params?: Router.UnknownInputParams; } | { pathname: `/image-server-select`; params?: Router.UnknownInputParams; } | { pathname: `/manga-reader`; params?: Router.UnknownInputParams; } | { pathname: `/ranobe-reader`; params?: Router.UnknownInputParams; } | { pathname: `/title-details`; params?: Router.UnknownInputParams; } | { pathname: `/webview`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | ``; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/anime-watch`; params?: Router.UnknownOutputParams; } | { pathname: `/demohtml`; params?: Router.UnknownOutputParams; } | { pathname: `/image-server-select`; params?: Router.UnknownOutputParams; } | { pathname: `/manga-reader`; params?: Router.UnknownOutputParams; } | { pathname: `/ranobe-reader`; params?: Router.UnknownOutputParams; } | { pathname: `/title-details`; params?: Router.UnknownOutputParams; } | { pathname: `/webview`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | ``; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/anime-watch${`?${string}` | `#${string}` | ''}` | `/demohtml${`?${string}` | `#${string}` | ''}` | `/image-server-select${`?${string}` | `#${string}` | ''}` | `/manga-reader${`?${string}` | `#${string}` | ''}` | `/ranobe-reader${`?${string}` | `#${string}` | ''}` | `/title-details${`?${string}` | `#${string}` | ''}` | `/webview${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bookmarks${`?${string}` | `#${string}` | ''}` | `/bookmarks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/menu${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/anime-watch`; params?: Router.UnknownInputParams; } | { pathname: `/demohtml`; params?: Router.UnknownInputParams; } | { pathname: `/image-server-select`; params?: Router.UnknownInputParams; } | { pathname: `/manga-reader`; params?: Router.UnknownInputParams; } | { pathname: `/ranobe-reader`; params?: Router.UnknownInputParams; } | { pathname: `/title-details`; params?: Router.UnknownInputParams; } | { pathname: `/webview`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | ``; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
